// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA971GnhbOln5Z374pDe5RywGQ6J30g1kM',
    appId: '1:893747460708:web:c5eb1172a63b59a769fd71',
    messagingSenderId: '893747460708',
    projectId: 'transform66-edc4d',
    authDomain: 'transform66-edc4d.firebaseapp.com',
    storageBucket: 'transform66-edc4d.appspot.com',
    measurementId: 'G-DJ44CT5MRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ-AX6msx4DaEIgKK7P4HnPBPFkqx9At4',
    appId: '1:893747460708:android:1d0e5330572e8a3469fd71',
    messagingSenderId: '893747460708',
    projectId: 'transform66-edc4d',
    storageBucket: 'transform66-edc4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsD0wYTX-3c_gUBs-3SDeJNFFaai30Rqs',
    appId: '1:893747460708:ios:faa43e9e34baa41f69fd71',
    messagingSenderId: '893747460708',
    projectId: 'transform66-edc4d',
    storageBucket: 'transform66-edc4d.appspot.com',
    iosBundleId: 'com.example.transform66',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsD0wYTX-3c_gUBs-3SDeJNFFaai30Rqs',
    appId: '1:893747460708:ios:006c758aa5f5d5ec69fd71',
    messagingSenderId: '893747460708',
    projectId: 'transform66-edc4d',
    storageBucket: 'transform66-edc4d.appspot.com',
    iosBundleId: 'com.example.transform66.RunnerTests',
  );
}